[mypy]
python_version = 3.9
warn_return_any = True
warn_unused_configs = True
ignore_missing_imports = True
follow_imports = silent

[mypy-src.*]
ignore_errors = True

[mypy-tests.*]
ignore_errors = False
