"""
Prometheus-format auth metrics collector for OWLBAN GROUP.

Self-contained (no prometheus_client dependency) so it runs anywhere,
including minimal Docker images. Emits Prometheus TEXT exposition format.

Collected metrics:
  owlban_auth_login_total            counter  {outcome, company}
  owlban_auth_token_generated_total   counter  {type}
  owlban_auth_token_refreshed_total   counter
  owlban_auth_api_key_generated_total counter  {company}
  owlban_auth_rate_limit_total        counter  {action}
  owlban_auth_lockout_total           counter
  owlban_auth_audit_events_total      counter  {event_type, severity}
  owlban_auth_active_sessions         gauge
  owlban_auth_account_lockouts        gauge
  owlban_auth_api_keys_active         gauge
"""

import threading
from collections import defaultdict


class MetricFamily:
    """A single named Prometheus metric backed by a label-tuple value map."""

    __slots__ = ("name", "help", "type", "_values")

    def __init__(self, name, help_text, metric_type="counter"):
        self.name = name
        self.help = help_text
        self.type = metric_type
        self._values = defaultdict(float)  # label-tuple -> value

    def labels(self):
        return {
            "owlban_auth_login_total": ("outcome", "company"),
            "owlban_auth_token_generated_total": ("type",),
            "owlban_auth_token_refreshed_total": (),
            "owlban_auth_api_key_generated_total": ("company",),
            "owlban_auth_rate_limit_total": ("action",),
            "owlban_auth_lockout_total": (),
            "owlban_auth_audit_events_total": ("event_type", "severity"),
            "owlban_auth_active_sessions": (),
            "owlban_auth_account_lockouts": (),
            "owlban_auth_api_keys_active": (),
        }.get(self.name, ())


class AuthMetrics:
    """Thread-safe registry of auth-related Prometheus metrics."""

    def __init__(self):
        self._lock = threading.Lock()
        self._families = {}
        definitions = [
            ("owlban_auth_login_total",
             "Total authentication attempts by outcome and company.", "counter"),
            ("owlban_auth_token_generated_total",
             "JWT tokens generated by type (access/refresh).", "counter"),
            ("owlban_auth_token_refreshed_total",
             "Refresh-token flow invocations.", "counter"),
            ("owlban_auth_api_key_generated_total",
             "API keys generated by company.", "counter"),
            ("owlban_auth_rate_limit_total",
             "Rate-limit rejections by action/path.", "counter"),
            ("owlban_auth_lockout_total",
             "Account lockouts triggered.", "counter"),
            ("owlban_auth_audit_events_total",
             "Audit events logged by severity/event_type.", "counter"),
            ("owlban_auth_active_sessions",
             "Currently tracked active sessions.", "gauge"),
            ("owlban_auth_account_lockouts",
             "Accounts currently locked out.", "gauge"),
            ("owlban_auth_api_keys_active",
             "Currently active API keys.", "gauge"),
        ]
        for name, help_text, mtype in definitions:
            self._families[name] = MetricFamily(name, help_text, mtype)

    def record_login(self, outcome, company="OWLBAN_GROUP"):
        """outcome in {success, invalid_credentials, inactive, locked}."""
        with self._lock:
            self._families["owlban_auth_login_total"]._values[(outcome, company)] += 1

    def record_token_generated(self, token_type="access"):
        with self._lock:
            self._families["owlban_auth_token_generated_total"]._values[(token_type,)] += 1

    def record_token_refreshed(self):
        with self._lock:
            self._families["owlban_auth_token_refreshed_total"]._values[()] += 1

    def record_api_key_generated(self, company="OWLBAN_GROUP"):
        with self._lock:
            self._families["owlban_auth_api_key_generated_total"]._values[(company,)] += 1

    def record_rate_limit(self, action="request"):
        with self._lock:
            self._families["owlban_auth_rate_limit_total"]._values[(action,)] += 1

    def record_lockout(self):
        with self._lock:
            self._families["owlban_auth_lockout_total"]._values[()] += 1

    def record_audit_event(self, event_type, severity="info"):
        with self._lock:
            self._families["owlban_auth_audit_events_total"]._values[(event_type, severity)] += 1

    def set_active_sessions(self, count):
        with self._lock:
            self._families["owlban_auth_active_sessions"]._values[()] = count

    def set_account_lockouts(self, count):
        with self._lock:
            self._families["owlban_auth_account_lockouts"]._values[()] = count

    def set_api_keys_active(self, count):
        with self._lock:
            self._families["owlban_auth_api_keys_active"]._values[()] = count

    def render(self):
        """Render all metrics in Prometheus TEXT exposition format."""
        lines = []
        for family in self._families.values():
            lines.append(f"# HELP {family.name} {family.help}")
            lines.append(f"# TYPE {family.name} {family.type}")
            names = family.labels()
            for label_tuple, value in sorted(family._values.items()):
                if names:
                    pairs = ",".join(f'{n}="{v}"' for n, v in zip(names, label_tuple))
                    suffix = "{" + pairs + "}"
                else:
                    suffix = ""
                if float(value).is_integer():
                    rendered = f"{family.name}{suffix} {int(value)}"
                else:
                    rendered = f"{family.name}{suffix} {value}"
                lines.append(rendered)
        return "\n".join(lines) + "\n"


# Singleton instance shared across the API server
auth_metrics = AuthMetrics()